version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    volumes:
    - .:/usr/src/app